/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kalug
 */
import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import core.FileHandler;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {

    initComponents();

    loadEmployeeTable();
}
    
    private void loadEmployeeTable() {

    try {

        FileHandler fileHandler = new FileHandler();

        String[][] employees =
                fileHandler.getEmployeesRecords();

        DefaultTableModel model =
                (DefaultTableModel) tblEmployees.getModel();

        // clear old rows
        model.setRowCount(0);

        for (String[] emp : employees) {

            model.addRow(new Object[] {

                emp[0], // Employee Number
                emp[1], // Last Name
                emp[2], // First Name
                emp[6], // SSS
                emp[7], // PhilHealth
                emp[8], // TIN
                emp[9]  // Pag-IBIG

            });
        }

    } catch (IOException e) {

        e.printStackTrace();

    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnAddEmployee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee No", "Last Name", "First Name", "SSS No", "PagIbig No", "TIN", "Philhealth No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployees);

        btnAddEmployee.setText("Add Employee");
        btnAddEmployee.addActionListener(this::btnAddEmployeeActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddEmployee))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddEmployee)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseClicked
     int selectedRow = tblEmployees.getSelectedRow();

if (selectedRow != -1) {

    String empNo =
            tblEmployees.getValueAt(selectedRow, 0).toString();

    String lastName =
            tblEmployees.getValueAt(selectedRow, 1).toString();

    String firstName =
            tblEmployees.getValueAt(selectedRow, 2).toString();

    String sss =
            tblEmployees.getValueAt(selectedRow, 3).toString();

    String philHealth =
            tblEmployees.getValueAt(selectedRow, 4).toString();

    String tin =
            tblEmployees.getValueAt(selectedRow, 5).toString();

    String pagIbig =
            tblEmployees.getValueAt(selectedRow, 6).toString();

    JOptionPane.showMessageDialog(

            this,

            "Employee No: " + empNo
            + "\nName: " + lastName + ", " + firstName
            + "\nSSS No: " + sss
            + "\nPhilHealth No: " + philHealth
            + "\nTIN: " + tin
            + "\nPag-IBIG No: " + pagIbig,

            "Employee Details",

            JOptionPane.INFORMATION_MESSAGE
    );
}
    }//GEN-LAST:event_tblEmployeesMouseClicked

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
      
   String empNo =
            JOptionPane.showInputDialog("Enter Employee Number:");

    String lastName =
            JOptionPane.showInputDialog("Enter Last Name:");

    String firstName =
            JOptionPane.showInputDialog("Enter First Name:");

    String sss =
            JOptionPane.showInputDialog("Enter SSS Number:");

    String philHealth =
            JOptionPane.showInputDialog("Enter PhilHealth Number:");

    String tin =
            JOptionPane.showInputDialog("Enter TIN:");

    String pagIbig =
            JOptionPane.showInputDialog("Enter Pag-IBIG Number:");

    // Validation
    if (empNo.isEmpty()
            || lastName.isEmpty()
            || firstName.isEmpty()) {

        JOptionPane.showMessageDialog(

                this,

                "Required fields cannot be empty.",

                "Validation Error",

                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    DefaultTableModel model =
            (DefaultTableModel) tblEmployees.getModel();

    // Duplicate check
    for (int i = 0; i < model.getRowCount(); i++) {

        String existingEmpNo =
                model.getValueAt(i, 0).toString();

        if (existingEmpNo.equals(empNo)) {

            JOptionPane.showMessageDialog(

                    this,

                    "Employee Number already exists.",

                    "Duplicate Error",

                    JOptionPane.ERROR_MESSAGE
            );

            return;
        }
    }

    try {

        FileHandler fileHandler = new FileHandler();

        fileHandler.addEmployeeRecord(

                empNo,
                lastName,
                firstName,
                sss,
                philHealth,
                tin,
                pagIbig
        );

        // Add row to JTable immediately
        model.addRow(new Object[] {

            empNo,
            lastName,
            firstName,
            sss,
            philHealth,
            tin,
            pagIbig
        });

        JOptionPane.showMessageDialog(

                this,

                "Employee added successfully."

        );

    } catch (IOException e) {

        JOptionPane.showMessageDialog(

                this,

                "Error saving employee.",

                "File Error",

                JOptionPane.ERROR_MESSAGE
        );
    }

    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables

}